{"name": "Проверка: нельзя авторизоваться в системе с несуществующим логином и существующим паролем", "status": "passed", "description": "Запрос POST на /api/v1/courier/login с несуществующим логином и существующим паролем вернет 404 Not Found", "start": 1742111084280, "stop": 1742111084643, "uuid": "9f317fb8-6d17-429e-9c6a-1c8ad0779121", "historyId": "74ecab81dfbaecab76dfd48f34a60e47", "testCaseId": "74ecab81dfbaecab76dfd48f34a60e47", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_wrong_login_return_404_not_found", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-FO1K8TG"}, {"name": "thread", "value": "15228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}